name: Deploy Power BI Report

on:
  push:
    branches:
      - main  # Change to your branch name

jobs:
  deploy:
    runs-on: windows-latest  # Use a Windows runner for PowerShell
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PowerShell
        uses: actions/setup-powershell@v2

      - name: Publish Power BI Report
        run: |
          $ReportPath = "${{ github.workspace }}/powerbi/test.pbix"  # Updated path to your PBIX file
          $ReportServerUri = "http://192.168.1.5/reportserver"  # Updated URL for Power BI Report Server
          $DestinationFolder = "/YourReportFolder"  # Specify your destination folder on the server

          # Call the deploy script
          .\deploy.ps1 -ReportPath $ReportPath -ReportServerUri $ReportServerUri -DestinationFolder $DestinationFolder -Overwrite $true
